'''Estas son las librería correspondientes para la conexión con mongoDb'''
import pymongo
import tkinter as tk
from tkinter import Scrollbar, messagebox, Frame

# Conexión con la base de datos mongoDb
myclient = pymongo.MongoClient('mongodb://localhost:27017/')
mydb = myclient['CasoUso']
mycol = mydb['CRUM']

'''Lista de parametros que se mostraran en la pantalla''' 
lst = [('Nº','Provincia','Cantón','Parroquia','Colegio')]

class BaseData:
    def callback(self,event):
        li=[]
        li=event.widget._values
        self.cid.set(lst[li[1]][0])
        self.cprovincia.set(lst[li[1]][1])
        self.ccanton.set(lst[li[1]][2])
        self.cparroquia.set(lst[li[1]][3])
        self.ccolegio.set(lst[li[1]][4])


    def creategrid(self,num):
        '''
            Método que ayudará a insertar, eliminar y modificar los datos.
            Además cumple la función de permitir ingresar caracteres especiales.
        '''
        lst.clear()
        lst.append(['Nº','Provincia','Cantón','Parroquia','Colegio'])
        cursor = mycol.find({})
        for text_fromDB in cursor:
            personid = int(text_fromDB['id'])
            provincia = str(text_fromDB['Provincia']).encode('utf_8').decode("utf_8")
            canton = str(text_fromDB['Cantón']).encode('utf_8').decode("utf_8")
            parroquia = str(text_fromDB['Parroquia']).encode('utf_8').decode("utf_8")
            colegio = str(text_fromDB['Colegio']).encode('utf_8').decode("utf_8")
            lst.append([personid,provincia,canton,parroquia,colegio])
        
        for interacion in range(len(lst)):
            for itera in range(len(lst[0])):
                mgrid = tk.Entry(self.window,width=11,font=('Arial',10,'bold'), bg='#c2a2db')
                mgrid.insert(tk.END,lst[interacion][itera])
                mgrid._values = mgrid.get(),interacion
                mgrid.grid(row=(interacion+10), column=(itera+4),padx=1,pady=2)
                mgrid.bind("<Button-1>", self.callback)

        if (num==1):
            for label in self.window.grid_slaves():
                if (int(label.grid_info()["row"]) > 3):
                    label.grid_forget()


    def msgbox(self,msg,titulobar):
        '''
            Permite enviar mensaje de información.

            PARAMETROS
            -----------
                msg: str
                    Es el mensaje que se imprimerá por pantalla
                titulobar: str
                    Es el título que contendrá la ventana

            Retorna
            ---------
                result
        '''
        result=messagebox.askokcancel(title=titulobar,message=msg)
        return result

    def guarda (self):
        '''
        Método que permite guardar un reegistro nuevo a la base de datos
        Atraves de los campos que se vallan a ingresar.
        '''
        rap=self.msgbox("Registro guardado","Registro")
        if (rap==True):
            newid = mycol.count_documents({})
            if (newid!=0):
                newid = mycol.find_one(sort=[('id',-1)])["id"]
            id=newid+1
            self.cid.set(id)
            mydict= {'id':int(self.custid.get()),'Provincia':self.custprovincia.get(),'Cantón':self.custcanton.get(),
                    'Parroquia':(self.custparroquia.get()),'Colegio':self.custcolegio.get()}
            agregaUno = mycol.insert_one(mydict)
            self.creategrid(1)
            self.creategrid(0)


    def elimina (self):
        '''
        Método que permite eliminar un reegistro nuevo a la base de datos
        Atraves de la id que se valla a ingresar.
        '''
        rap=self.msgbox("Registro eliminado","Eliminar")
        if (rap==True):
            myquerry = {'id':int(self.custid.get())}
            mycol.delete_one(myquerry)
        self.creategrid(1)
        self.creategrid(0)


    def limpiar(self):
            '''
            Método que limpia los Entry de la interfaz gráfica dejando todo como nuevo.
            '''
            self.cprovincia.set('')
            self.ccanton.set('')
            self.cparroquia.set('')
            self.ccolegio.set('')

    def modifica (self):
        '''
            Método que permite modificar un registro nuevo a la base de datos
            Atraves del id que se valla a ingresar.
        '''
        rap=self.msgbox("Registro modificado","Modificar")
        if rap == True:
            myquerry = {'id':int(self.custid.get())}
            newvalues = {"$set":{"Provincia":self.custprovincia.get()}}
            mycol.update_one(myquerry,newvalues)

            newvalues = {"$set":{"Cantón":self.custcanton.get()}}
            mycol.update_one(myquerry,newvalues)

            newvalues = {"$set":{"Parroquia":self.custparroquia.get()}}
            mycol.update_one(myquerry,newvalues)

            newvalues = {"$set":{"Colegio":self.custcolegio.get()}}
            mycol.update_one(myquerry,newvalues)

            self.creategrid(1)
            self.creategrid(0)

    def __init__ (self):
        '''
        Método constructor de las interfaces gráficas.
        '''
        #Ventana principal.
        self.window = tk.Tk()
        self.window.title("CURD de Caso de Uso")
        self.window.geometry("415x650")
        self.window.config(bg="gray22")
        #Sub ventanas
        self.frame1 = Frame(self.window)
        self.frame1.grid(columnspan=14,column=0,row=0)
        self.frame2 = Frame(self.window, bg='#4779b2')
        self.frame2.grid(columnspan=14,column=0, row=1)
        self.frame4 = Frame(self.window, bg='#4779b2')
        self.frame4.grid(columnspan=14,column=0, row=3,pady=5)
        
        #-------------------------- Label y Entry del la interfaz --------------------------

        self.label=tk.Label(self.frame1, text = 'M I E S - I N F A',bg='gray22',fg='white', font=('Orbitron',15,'bold'))
        self.label.grid(column=0, row=0)

        self.label = tk.Label(self.frame2, text='Escoger Datos',fg='gray90', bg ='#4779b2', font=('Rockwell',12,'bold'))
        self.label.grid(columnspan=3, column=0,row=0, pady=10)

        self.label = tk.Label(self.frame2, text='Nº',fg='white', bg ='#4779b2', font=('Rockwell',11,'bold'))
        self.label.grid(column=1,row=2)
        self.cid= tk.StringVar()
        self.custid = tk.Entry(self.frame2, textvariable=self.cid,width=21)
        self.custid.grid(column=2,row=2)
        self.custid.configure(state=tk.DISABLED)

        self.label = tk.Label(self.frame2, text='Provincias',fg='white', bg ='#4779b2', font=('Rockwell',11,'bold'))
        self.label.grid(column=1,row=3)
        self.cprovincia = tk.StringVar()
        self.custprovincia = tk.Entry(self.frame2, textvariable=self.cprovincia,width=21)
        self.cprovincia.set('Elegir opcion')
        self.Provincias=['Azuay','Bolívar','Cañar','Carchi','Chimborazo',
            'Cotopaxi','El Oro','Esmeraldas','Galápagos','Guayas',
            'Imbabura','Loja','Los Ríos','Manabí','Morona Santiago',
            'Napo','Orellana','Pastaza','Pichincha','Santa Elena',
            'Santo Domingo de los Tsáchilas	','Sucumbíos','Tungurahua','Zamora Chinchipe']
        self.listPro=tk.OptionMenu(self.frame2,self.cprovincia,*self.Provincias)
        self.listPro.config(width=15, height=1,bg= "white")
        self.listPro.grid(column=2,row=3)


        self.label = tk.Label(self.frame2, text='Canton',fg='white', bg ='#4779b2', font=('Rockwell',11,'bold'))
        self.label.grid(column=1,row=4)
        self.ccanton = tk.StringVar()
        self.custcanton = tk.Entry(self.frame2, textvariable=self.ccanton,width=21)
        self.ccanton.set('Elegir opcion')
        self.cantones=['Cuenca','Giron ','Gualaceo','Nabon','Paute ','Pucara ','San Fernando ','Santa Isabel','Sigsig','Oña','Chordeleg','El Pan','Sevilla de Oro',
                            'Guachapala','Camilo Ponce Enriquez','Guaranda','Chilanes','Chimbo','Echeandia','San Miguel','Caluma','Las Naves','Azogues','Biblian',
                            'Cañar','La Troncal','El Tambo','Deleg','Suscal','Tulcan','Bolivar','Espejo','Mira','Montufar','San Pedro de Huaca','Latacunga','La Mana',
                            'Pangua','Pujili','Salcedo','Saquisili','Sigchos','Riobamba','Alausi','Colta','Chambo','Chunchi','Guamote','Guano','Pallatanga','Penipe',
                            'Cumanda','Machala','Arenillas','Atahualpa','Balsas','Chilla','El Guabo','Huaquillas','Marcabeli','Pasaje','Piñas','Portovelo','Santa Rosa',
                            'Zaruma','Las Lajas','Esmeraldas','Eloy Alfaro','Muisne','Quininde','San Lorenzo','Atacames','Rioverde','La Concordia','Guayaquil',
                            'Alfredo Baquerizo','Balao','Balzar','Colimes','Daule','Duran','El Empalme','El Triunfo','Milagro','Naranjal','Naranjito','Palestina',
                            'Pedro Carbo','Samborondon','Santa Lucia','Salitre','San Jacinto de Yaguachi','Playas','Simon Bolivar','Coronel Marcelino Maridueña',
                            'Lomas de Sargentillo','Nobol','General Elizalde(Bucay)','Isidro Ayora','Ibarra','Atonio Ante','Cotacachi','Otavalo','Pimampiro',
                            'San Miguel de Urcuqui','Loja','Calvas','Catamayo','Celica','Chaguarpamba','Espindola','Gonzanama','Macara','Paltas','Puyango','Saraguro',
                            'Sozoranga','Zapotillo','Pindal','Quilanga','Olmedo','Babahoyo','Baba','Montalvo','Puebloviejo','Quevedo','Urdaneta','Ventanas','Vinces',
                            'Palenque','Buena Fe','Valencia','Mocache','Quinsaloma','Portoviejo','Bolivar','Chone','El Carmen','Flavio Alfaro','Jipijapa','Junin',
                            'Manta','Montecristi','Pajan','Pichincha','Rocafuerte','Santa Ana','Sucre','Tosagua','24 de Mayo','Pedernales','Olmedo','Puerto Lopez',
                            'Jama','Jarmijo','San Vicente','Morona','Gualaquiza','Limon Indanza','Palora','Santiago','Sucua','Huamboya','San Juan Bosco','Taisha',
                            'Logroño','Pablo Sexto','Tiwintza','Tena','Archidona','El Chaco','Quijos','Carlos Julio Arosemena Tola','Pastaza','Mera','Santa Clara',
                            'Arajuno','Quito','Cayambe','Mejia','Pedro Moncayo','Rumañahui','San Miguel de los Bancos','Pedro Vicente Maldonado','Puerto Quito',
                            'Ambato','Baños de Agua Santa','Cevallos','Mocha','Patate','Quero','San Pedro de Pelileo','Santiago de Pillaro','Tisaleo','Zamora',
                            'Chinchipe','Nangaritza','Yacuambi','Yantzaza','El Pangui','Centinela del Condor','Palanda','Paquisha','San Cristobal','Isabela',
                            'Santa Cruz','Lago Agrio','Gonzalo Pizarro','Putumayo','Shushufindi','Sucumbios','Cascales','Cuyabeno','Orellana','Aguarico',
                            'La Joya de los Sachas','Loreto','Santo Domingo de los Colorados','Santa Elena','La Libertad']
        self.listCan=tk.OptionMenu(self.frame2,self.ccanton,*self.cantones)
        self.listCan.config(width=15, height=1,bg= "white")
        self.listCan.grid(column=2,row=4)


        self.label = tk.Label(self.frame2, text='Parroquia',fg='white', bg ='#4779b2', font=('Rockwell',11,'bold'))
        self.label.grid(column=1,row=5)
        self.cparroquia = tk.StringVar()
        self.custparroquia = tk.Entry(self.frame2, textvariable=self.cparroquia,width=21)
        self.cparroquia.set('Elegir opcion')
        self.parroquias=['Bellavista','Cañaribamba','El Batan',
                        'El Sagrario',
                        'El Vecino',
                        'Gil Ramirez Davalos',
                        'Huaynacapac',
                        'Machangara',
                        'Monay',
                        'San Blas',
                        'San Sebastian',
                        'Sucre',
                        'Totoracocha',
                        'Yanuncay',
                        'Hermano Miguel',
                        'Cuenca',
                        'Baños',
                        'Cumbe',
                        'Chaucha',
                        'Checa(Jidcay)',
                        'Chiquintad',
                        'Llacao',
                        'Molleturo',
                        'Nulti',
                        'Octavio Cordero Palacios(SantaRosa)',
                        'Paccha',
                        'Quingeo',
                        'Ricaurte',
                        'San Joaquin',
                        'Santa Ana',
                        'Sayausi',
                        'Sidcay',
                        'Sinincay',
                        'Tarqui',
                        'Turi',
                        'Valle',
                        'Victoria del Portete(Irquis)',
                        'Giron',
                        'Asuncion',
                        'San Gerardo',
                        'Gualaceo',
                        'Daniel Cordova Toral(El Oriente)',
                        'Jadan',
                        'Mariano Moreno',
                        'Remigio Crespo Toral(Gulag)',
                        'San Juan',
                        'Zhidmad',
                        'Luis Cordero Vega',
                        'Simon Bolivar',
                        'Nabon',
                        'Cochapata',
                        'El Progreso',
                        'Las Nieves(Chaya)',
                        'La Paz',
                        'Paute',
                        'Bulan(Jose Victor Izquiero)',
                        'Chican(Guillermo Ortega)',
                        'El Cabo',
                        'Guarainag',
                        'San Cristobal(Carlos Ordoñez Lazo)',
                        'Tomebamba',
                        'Dug Dug',
                        'Pucara',
                        'San Rafael de Sharug',
                        'San Fernando',
                        'Chumblin',
                        'Santa Isabel',
                        'Abdon Calderon(La Union)',
                        'Zhaglli',
                        'Sigsig',
                        'Cuchil',
                        'Jima',
                        'Guel',
                        'Ludo',
                        'San Bartolome',
                        'San Jose de Raranga',
                        'San Felipe de Oña',
                        'Susudel',
                        'Chordeleg',
                        'Principal',
                        'La Union',
                        'Luis Galarza Orellana',
                        'San Martin de Puzhio',
                        'El Pan',
                        'San Vicente',
                        'Sevilla de Oro',
                        'Amaluza',
                        'Palmas',
                        'Guachapala',
                        'Camilo Ponce Enriquez',
                        'El Carmen de Pijili',
                        'Angel Polibio Chaves',
                        'Gabriel ignacio Veintimilla',
                        'Guanujo',
                        'Guaranda',
                        'Facundo Vela',
                        'Julio E. Moreno',
                        'Salinas',
                        'San Lorenzo',
                        'San Simon',
                        'Santa Fe',
                        'Simiatug',
                        'San Luis de Pambil',
                        'Chilanes',
                        'San Jose del Tambo',
                        'San Jose de Chimbo',
                        'Asuncion',
                        'Magdalena',
                        'San Sebastian',
                        'Telimbela',
                        'Echeandia',
                        'San Miguel',
                        'Balsapamba',
                        'Bilovan',
                        'Regulo de Mora',
                        'San Pablo',
                        'Santiago',
                        'San Vicente',
                        'Caluma',
                        'Las Mercedes',
                        'Las Naves',
                        'Aurelio Bayas Martinez',
                        'Azogues',
                        'Borrero',
                        'San Francisco',
                        'Azogues',
                        'Cojitambo',
                        'Guapan',
                        'Javier Loyola',
                        'Luis Cordero',
                        'Pindilig',
                        'Rivera',
                        'San Miguel',
                        'Taday',
                        'Biblian',
                        'Nazon',
                        'San Francisco de Saego',
                        'Turupamba',
                        'Jerusalen',
                        'Cañar',
                        'Chontamarca',
                        'Chorocopte',
                        'General Morales',
                        'Gualleturo',
                        'Honorato Vasquez',
                        'Ingapirca',
                        'Juncal',
                        'San Antonio',
                        'Zhud',
                        'Ventura',
                        'Ducur',
                        'La Troncal',
                        'Manuel J. Calle',
                        'Pancho Negro',
                        'El Tambo',
                        'Deleg',
                        'Solano',
                        'Suscal',
                        'Gonzalez Suarez',
                        'Tulcan',
                        'Tulcan',
                        'El carmelo',
                        'Julio Andrades(Orejuela)',
                        'Maldonado',
                        'Pioter',
                        'Tobar Donoso',
                        'Tufiño',
                        'Urbina(Taya)',
                        'El Chical',
                        'Santa Martha de Cuba',
                        'Bolivar',
                        'Garcia Moreno',
                        'Los Andes',
                        'Monte Olivo',
                        'San Vicente de Pusir',
                        'San Rafael',
                        'El Angel',
                        '27 de Septiembre',
                        'El Angel',
                        'El Goaltal',
                        'La Libertad(Alizo)',
                        'San Isidro',
                        'Mira(Chontahuasi)',
                        'Concepcion',
                        'Jijon y Caamaño',
                        'Juan Montalvo(San Ignacio de Quil)',
                        'Gonzalez Suarez',
                        'San Jose',
                        'San Gabriel',
                        'Cristobal Colon',
                        'Chitan de Navarrete',
                        'Fernandez Salvador',
                        'La Paz',
                        'Piartal',
                        'Huaca',
                        'Mariscal Sucre',
                        'Eloy Alfaro(San Felipe)',
                        'Ignacio Flores',
                        'Juan Montalvo(San Sebastian)',
                        'La Matriz',
                        'San Buenaventura',
                        'Alaques',
                        'Belisario Quevedo',
                        'Guaytacama',
                        'Joseguango Bajo',
                        'Mulalo',
                        '11 de Noviembre(Ilinchisi)',
                        'Poalo',
                        'San Juan de Pastocalle',
                        'Tanicuchi',
                        'Toacaso',
                        'El Carmen',
                        'La Mana',
                        'El Triunfo',
                        'La Mana',
                        'Guasaganda',
                        'Pucayacu',
                        'El Corazon',
                        'Moraspungo',
                        'Pinllopata',
                        'Ramon Campaña',
                        'Pujili',
                        'Angamarca',
                        'Guangaje',
                        'La Victoria',
                        'Pilalo',
                        'Tingo',
                        'Zumbahua',
                        'San Miguel',
                        'Antonio Jose Holguin(Santa Lucia)',
                        'Cusubamba',
                        'Mulalillo',
                        'Mulliquindil(Santa Ana)',
                        'Pansaleo',
                        'Saquisili',
                        'Canchagua',
                        'Chantilin',
                        'Cochapamba',
                        'Sigchos',
                        'Chugchilan',
                        'Isinlivi',
                        'Las Palmas',
                        'Palo Quemado',
                        'Lizarzaburu',
                        'Maldonado',
                        'Velasco',
                        'Veloz',
                        'Yaruquies',
                        'Lican',
                        'Riobamba',
                        'Cacha',
                        'Calpi',
                        'Cubijies',
                        'Flores',
                        'Lican',
                        'Licto',
                        'Pungala',
                        'Punin',
                        'Quimiag',
                        'San Juan',
                        'San Luis',
                        'Alausi',
                        'Achupallas',
                        'Guasuntos',
                        'Huigra',
                        'Multitud',
                        'Pistishi(Nariz del Diablo)',
                        'Pumallacta',
                        'Sevilla',
                        'Sibambe',
                        'Tixan',
                        'Cajabamba',
                        'Sicalpa',
                        'Villa la Union (Cajabamba)',
                        'Cañi',
                        'Columbe',
                        'Juan de Velasco(Pangor)',
                        'Santiago de Quito',
                        'Chambo',
                        'Chunchi',
                        'Capzol',
                        'Compud',
                        'Gonzol',
                        'Llagos',
                        'Guamote',
                        'Cebadas',
                        'Palmira',
                        'El Rosario',
                        'La Matriz',
                        'Guano',
                        'Guanando',
                        'Ilapo',
                        'La Providencia',
                        'San Andres',
                        'San Gerardo de Pacaicaguan',
                        'San Isisdro de Patulu',
                        'San Jose del Chazo',
                        'Santa Fe de Galan',
                        'Valparaiso',
                        'Pallatanga',
                        'Penipe',
                        'El Altar',
                        'Matus',
                        'Puela',
                        'San Antonio de Bayushig',
                        'La Candelaria',
                        'Bilbao',
                        'Cumanda',
                        'Cumanda',
                        'La Providencia',
                        'Machala',
                        'Puerto Bolivar',
                        'Nueve de Mayo',
                        'El Cambio',
                        'Jambeli',
                        'Jubones',
                        'Machala',
                        'El Retiro',
                        'Arenillas',
                        'Chacras',
                        'Palmales',
                        'Carcabon',
                        'Paccha',
                        'Ayapamba',
                        'Cordoncillo',
                        'Milagro',
                        'San Jose',
                        'San Juan de Cerro Azul',
                        'Balsas',
                        'Bellamaria',
                        'Chilla',
                        'El Guabo',
                        'Barbones(Sucre)',
                        'La Iberia',
                        'Tendales',
                        'Rio bonito',
                        'Ecuador',
                        'El Paraiso',
                        'Hualtaco',
                        'Milton Reyes',
                        'Union Lojana',
                        'Huaquillas',
                        'Marcabeli',
                        'El Ingenio',
                        'Bolivar',
                        'Loma de Franco',
                        'Ochoa Leon',
                        'Tres Cerritos',
                        'Pasaje',
                        'Buenavista',
                        'Casacay',
                        'La Peaña',
                        'Progreso',
                        'Uzhcurrumi',
                        'Cañaquemada',
                        'La Matriz',
                        'La Susaya',
                        'Pinas Grande',
                        'Pinas',
                        'Piñas',
                        'Capiro',
                        'La Bocana',
                        'Moromoro',
                        'Piedras',
                        'San Roque(Ambrosio Maldonado)',
                        'Saracay',
                        'Portovelo',
                        'Curtincapa',
                        'Morales',
                        'Salati',
                        'Santa Rosa',
                        'Puerto Jeli',
                        'Jambeli(Satelite)',
                        'Jumon',
                        'Nuevo Santa Rosa',
                        'Santa Rosa',
                        'Bellavista',
                        'Jambeli',
                        'La Avanzada',
                        'San Antonio',
                        'Torata',
                        'Victoria',
                        'Bellamaria',
                        'Zaruma',
                        'Abañin',
                        'Arcapamba',
                        'Guanazan',
                        'Guizhaguiña',
                        'Huertas',
                        'Malvas',
                        'Muluncay Grande',
                        'Sinsao',
                        'Salvias',
                        'La Victoria',
                        'Platanillos',
                        'Valle Hermoso',
                        'La Victoria',
                        'La Libertad',
                        'El Paraiso',
                        'San Isidro',
                        'Bartolome Ruiz',
                        '5 de Agosto',
                        'Esmeraldas',
                        'Luis Tello(Las Palmas)',
                        'Simon Plata Torres',
                        'Esmeraldas',
                        'Camarones',
                        'Crnl. Carlos Concha Torres',
                        'Chinca',
                        'Majua',
                        'San Mateo',
                        'Tabiazo',
                        'Tachina',
                        'Vuelta Larga',
                        'Valdez',
                        'Anchayacu',
                        'Atahualpa',
                        'Borbon',
                        'La Tola',
                        'Luis Vargas Torres',
                        'Maldonado',
                        'Pampanal de Bolivar',
                        'San Francisco de Onzole',
                        'Santo de Domingo de Onzole',
                        'Selva Alegre',
                        'Telembi',
                        'Colon Eloy del Maria',
                        'San Jose de Cayapas',
                        'Timbire',
                        'Muisne',
                        'Bolivar',
                        'Daule',
                        'Galera',
                        'Quingue(Olmedo Perdono Franco)',
                        'Salima',
                        'San Francisco',
                        'San Gregorio',
                        'San Jose de Chamanga',
                        'Rosa zarate(Quininde)',
                        'Cube',
                        'Chura',
                        'Malimpia',
                        'Viche',
                        'La Union',
                        'San Lorenzo',
                        'Alto Tambo',
                        'Ancon',
                        'Calderon',
                        'Carondelt',
                        '5 de Junio',
                        'Concepcion',
                        'Mataje',
                        'San Javier de Cachavi',
                        'Santa Rita',
                        'Tambillo',
                        'Tululbi',
                        'Urbina',
                        'Atacames',
                        'La Union',
                        'Sua',
                        'Tonchigue',
                        'Tonsupa',
                        'Rioverde',
                        'Chontaduro',
                        'Chumunde',
                        'Lagarto',
                        'Montalñvo',
                        'Rocafuerte',
                        'La Concordia',
                        'Ludo',
                        'Ayacucho',
                        'Bolivar(Sagrario)',
                        'Carbo (Concepcion)',
                        'Febres Cordero',
                        'Garcia Moreno',
                        'Letamendi',
                        'Nueve de Octubre',
                        'Olmedo(San Alejo)',
                        'Roca',
                        'Rocafuerte',
                        'Sucre',
                        'Tarqui',
                        'Urdaneta',
                        'Ximena',
                        'Pascuales',
                        'Guayaquil ',
                        'Juan Gomez Rendon(Progreso)',
                        'Morro',
                        'Posorja',
                        'Puna',
                        'Tenguel',
                        'Chongon',
                        'Alfredo Baquerizo Moreno',
                        'Balao',
                        'Balzar',
                        'Colimes',
                        'San Jacinto',
                        'Daule',
                        'La Aurora (Satelite)',
                        'Banife',
                        'Emiliano Caicedo Marcos',
                        'Magro',
                        'Padre Juan Bautista Aguirre',
                        'Santa Clara',
                        'Vicente Piedrahita',
                        'Daule',
                        'Juan Bautista Aguirre',
                        'Laurel',
                        'Limonal',
                        'Los Lojas',
                        'Eloy Alfaro',
                        'El Recreo',
                        'Eloy Alfaro (Duran)',
                        'Velasco Ibarra(El Empalme)',
                        'Guayas (Pueblo Nuevo)',
                        'El Rosario',
                        'El Triunfo',
                        'Milagro',
                        'Chobo',
                        'Mariscal Sucre(Huaques)',
                        'Roberto Astudillo',
                        'Naranjal',
                        'Jesus Maria',
                        'San Carlos',
                        'Santa Rosa de Flandes',
                        'Taura',
                        'Naranjito',
                        'Palestina',
                        'Pedro Carbo',
                        'Valle de la Virgen',
                        'Sabanilla',
                        'Sanborondon',
                        'La Puntilla',
                        'Samborondon',
                        'Tarifa',
                        'Santa Lucia',
                        'Bocana',
                        'Candilejos',
                        'Central',
                        'Paraiso',
                        'San Mateo',
                        'El Salitre (Las Ramas)',
                        'Grnl. Vernaza(Dos Esteros)',
                        'La Victoria(Ñauza)',
                        'Junquillal',
                        'San Jacinto de Yaguachi',
                        'Gral. Pedro J. Montero(Boliche)',
                        'Yaguachi Viejo(Cone)',
                        'Virgen de Fatima',
                        'General Villamil(Playas)',
                        'Simon Bolivar',
                        'Crnl.Lorenzo de Garaicoa(Pedregal)',
                        'Coronel Marcelino Maridueña(San Carlos)',
                        'Lomas de Sargentillo',
                        'Narcisa de Jesus(Nobol)',
                        'General Antonio Elizalde(Bucay)',
                        'Isidro Ayora',
                        'Caranqui',
                        'Guayaquil de Alpachaca',
                        'Sagrario',
                        'San Francisco',
                        'Las Dolorosa del Priorato',
                        'San Miguel de Ibarra',
                        'Ambuqui',
                        'Angochagua',
                        'Carolina',
                        'La Esperanza',
                        'Lita',
                        'Salinas',
                        'San Antonio',
                        'Andrade Marin(Lourdes)',
                        'Atuntaqui',
                        'Atuntaqui',
                        'Imbaya(San Luis de Cobuendo)',
                        'San Francisco de Natabuela',
                        'San Jose de Chaltura',
                        'San Roque',
                        'Sagrario',
                        'San Francisco',
                        'Cotacachi',
                        'Apuela',
                        'Garcia Moreno(Llurimagua)',
                        'Imantag',
                        'Peñaherrera',
                        'Plaza Gutierrez(Calvario)',
                        'Quiroga',
                        '6 de Julio de Cuellaje',
                        'Vacas Galindo',
                        'Jordan',
                        'San Luis',
                        'Otavalo',
                        'Dr. Miguel Egas Cabezas(Peguche)',
                        'Eugenio Espejo(Calpaqui)',
                        'Gonzales Suarez',
                        'Pataqui',
                        'San Jose de Quichinche',
                        'San Juan de Iluman',
                        'San Pablo',
                        'San Rafael',
                        'Selva Alegre',
                        'Pimampiro',
                        'Chuga',
                        'Mariano Acosta',
                        'San Francisco de Sigsipamba',
                        'Urcuqui',
                        'Cahuasqui',
                        'La Merced de Buenos Aires',
                        'Pablo Arenas',
                        'San Blas',
                        'Tumbario',
                        'El Sagrario',
                        'San Sebastian',
                        'Sucre',
                        'Valle',
                        'Loja',
                        'Chantaco',
                        'Chuquiribamba',
                        'El Cisne',
                        'Gualel',
                        'Jimbilla',
                        'Malacatos(Valladolid)',
                        'San Lucas',
                        'San Pedro de Vilcabamba',
                        'Santiago',
                        'Taquil(Miguel Riofrio)',
                        'Vilcabamba(Victoria)',
                        'Yangana(Arsenio Castillo)',
                        'Quinara',
                        'Cariamanga',
                        'Chile',
                        'San Vicente',
                        'Cariamanga',
                        'Colaisaca',
                        'El Lucero',
                        'Utana',
                        'Sanguillin',
                        'Catamayo',
                        'San Jose',
                        'Catamayo (La Tola)',
                        'El Tambo',
                        'Guayquichuma',
                        'San POedro de la Bendita',
                        'Zambi',
                        'Celica',
                        'Cruzpamba',
                        'Pozul(San Juan de Pozul)',
                        'Sabanilla',
                        'Tnte. Maximiliano Rodriguez Loaiza',
                        'Chaguarpamba',
                        'Buenavista',
                        'El Rosario',
                        'Santa Rufina',
                        'Amarillos',
                        'Amaluza',
                        'Bellavista',
                        'Jimbura',
                        'Santa Teresita',
                        '27 de Abril',
                        'El Ingenio',
                        'El Airo',
                        'Nambacola',
                        'Purunuma(Eguiguren)',
                        'Sacapalca',
                        'Gonzamana',
                        'Changaimina(La Libertad)',
                        'Nambacola',
                        'Purunuma(Eguiguren)',
                        'Sacapalca',
                        'General Eloy Alfaro(San Sebastian)',
                        'Macara(Manuel Enrique Rengel Suquilanda)',
                        'Macara',
                        'Larama',
                        'La Victoria',
                        'Sabiango',
                        'Catacocha',
                        'Lourdes',
                        'Catacocha',
                        'Cangonama',
                        'Guachanama',
                        'Lauro Guerrero',
                        'Orianga',
                        'San Antonio',
                        'Casanga',
                        'Yamana',
                        'Alamor',
                        'Ciano',
                        'El Arenal',
                        'El Limo(Mariana de Jesus)',
                        'Mercadillo',
                        'Vicentino',
                        'Saraguro',
                        'El Paraiso de Celen',
                        'El Tablon',
                        'Lluzhapa',
                        'Manu',
                        'San Antonio de Qumbe(Cumbe)',
                        'San Pablo de Tenta',
                        'San Sebastian de Yuluc',
                        'Selva Alegre',
                        'Urdaneta(Paquishapa)',
                        'Sumaypamba',
                        'Sozoranga',
                        'Nueva Fatima',
                        'Tacamoros',
                        'Zapotillo',
                        'Cazaderos',
                        'Garzareal',
                        'Limones',
                        'Paletillas',
                        'Bolaspamba',
                        'Pindal',
                        'Chaquinal',
                        '12 de Diciembre',
                        'Quilanga',
                        'Fundochamba',
                        'San Antonio de las Aradas',
                        'Olmedo',
                        'La Tingue',
                        'Clemente Baquerizo',
                        'Dr. Camilo Ponce',
                        'Barreiro',
                        'El Salto',
                        'Babahoyo',
                        'Caracol',
                        'Febres Cordero(Las JUntas)',
                        'Pimocha',
                        'La Union',
                        'Baba',
                        'Guare',
                        'Isla de Bejucal',
                        'Montalvo',
                        'Puebloviejo',
                        'Puerto Peniche',
                        'San Juan',
                        'Quevedo',
                        'San Camilo',
                        'Guayacan',
                        'Nicolas Infante Diaz',
                        'San Cristobal',
                        'Siete de Octubre',
                        '24 de Mayo',
                        'Venus del Rio Quevedo',
                        'Viva Alfaro',
                        'Quevedo',
                        'San Carlos',
                        'La Esperanza',
                        'Catarama',
                        'Ricaurte',
                        'Ventanas',
                        'Zapotal',
                        'Vinces',
                        'Antonio Sotomayor',
                        'Palenque',
                        'San Jacinto de Buena Fe',
                        '7 de Agosto',
                        '11 de Octubre',
                        'San Jacinto de Buena Fe',
                        'Patricia Pilar',
                        'Valencia',
                        'Mocache',
                        'Quinsaloma',
                        'Portoviejo',
                        '12 de Marzo',
                        'Colon',
                        'Picoaza',
                        'San Pablo',
                        'Andres de Vera',
                        '18 de Octubre',
                        'Francisco Pacheco',
                        'Simon Bolivar',
                        'Picuaza',
                        'Portoviejo',
                        'Abdon Calderon (San Francisco)',
                        'Alhajuela (Bajo Grande)',
                        'Crucita',
                        'Pueblo Nuevo',
                        'Riochico (Rio Chico)',
                        'San Placido',
                        'Chirijos',
                        'Calceta',
                        'Membrillo',
                        'Quiroga',
                        'Chone',
                        'Santa Rita',
                        'Chone',
                        'Boyaca',
                        'Canuto',
                        'Convento',
                        'Chibunga',
                        'Eloy Alfaro',
                        'Ricaurte',
                        'San Antonio',
                        'El Carmen',
                        '4 de Diciembre',
                        'El Carmen',
                        'Wilfrido Loor Moreira (Maicito)',
                        'San Pedro de Suma',
                        'Flavio Alfaro',
                        'San Francisco de Novillo',
                        'Zapallo',
                        'Dr. Miguel Moran Lucio',
                        'Manuel Inocencio Parrales y Guale',
                        'San Lorenzo de Jipijapa',
                        'Jipijapa',
                        'America',
                        'El Anegado',
                        'Julcuy',
                        'La Union',
                        'Membrillal',
                        'Pedro Pablo Gomez',
                        'Puerto de Cayo',
                        'Junin',
                        'Los Esteros',
                        'Manta',
                        'San Mateo',
                        'Tarqui',
                        'Eloy Alfaro',
                        'Manta',
                        'San Lorenzo',
                        'Santa Marianita (Boca de Pacoche)',
                        'Anibal San Andres',
                        'Montecristi',
                        'El Colorado',
                        'General Eloy Alfaro',
                        'Leonidas Proaño',
                        'Montecristi',
                        'La Pila',
                        'Pajan',
                        'Campozano (La Palma de Pajan)',
                        'Cascol',
                        'Guale',
                        'Lascano',
                        'Pichincha',
                        'Barraganete',
                        'San Sebastian',
                        'Rocafuerte',
                        'Santa Ana',
                        'Lodana',
                        'Santa Ana de Vuelta Larga',
                        'Ayacucho',
                        'Honorato Vasquez',
                        'La Union',
                        'San Pablo (Cab. en Pueblo Nuevo)',
                        'Bahia de Caraquez',
                        'Leonidas Plaza Gutierrez',
                        'Bahia de Caraquez',
                        'Charapoto',
                        'San Isidro',
                        'Tosagua',
                        'Bachillero',
                        'Angel Pedro Giler (La Estancilla)',
                        'Sucre',
                        'Bellavista',
                        'Noboa',
                        'Arq. Sixto Duran Ballen',
                        'Pedernales',
                        'Cojimies',
                        '10 de Agosto',
                        'Atahualpa',
                        'Olmedo',
                        'Puerto Lopez',
                        'Machalilla',
                        'Salango',
                        'Jama',
                        'Jaramijo',
                        'San Vicente',
                        'Canoa',
                        'Macas',
                        'Alshi (Cab. En 9 de Octubre)',
                        'General Proaño',
                        'San Isidro',
                        'Sevilla Don Bosco',
                        'Sinai',
                        'Zuña (Zuñac)',
                        'Cuchaentza',
                        'Rio Blanco',
                        'Gualaquiza',
                        'Mercedes Molina',
                        'Amazonas (Rosario de Cuyes)',
                        'Bermejos',
                        'Bomboiza',
                        'Chigüinda',
                        'El Rosario',
                        'Nueva Tarqui',
                        'San Miguel de Cuyes',
                        'El Ideal',
                        'General Leonidas Plaza Gutierrez (Limon)',
                        'Indanza',
                        'San Antonio (Cab. En San Antonio Centro)',
                        'San Miguel de Conchay',
                        'Santa Susana de Chiviaza (Cab. En Chiviaza)',
                        'Yunganza (Cab. En El Rosario)',
                        'Palora (Metzera)',
                        'Arapicos',
                        'Cumanda',
                        'Sangay',
                        '16 de Agosto',
                        'Santiago de Mendez',
                        'Copal',
                        'Chupianza',
                        'Patuca',
                        'San Luis de El Acho',
                        'Tayuza',
                        'San Francisco de Chinimbimi',
                        'Sucua',
                        'Asuncion',
                        'Huambi',
                        'Santa Marianita de Jesus',
                        'Huamboya',
                        'Chiguaza',
                        'San Juan Bosco',
                        'Pan de Azucar',
                        'San Carlos de Limon',
                        'San Jacinto de Wakambeis',
                        'Santiago de Pananza',
                        'Taisha',
                        'Huasaga',
                        'Macuma',
                        'Tuutinentza',
                        'Pumpuentsa',
                        'Logroño',
                        'Yaupi',
                        'Shimpis',
                        'Pablo Sexto',
                        'Santiago',
                        'San Jose de Morona',
                        'Tena',
                        'Ahuano',
                        'Chontapunta',
                        'Pano',
                        'Puerto Misahualli',
                        'Puerto Napo',
                        'Talag',
                        'Muyuna',
                        'Archidona',
                        'Cotundo',
                        'San Pablo de Ushpayacu',
                        'El Chaco',
                        'Gonzalo Diaz de Pineda (El Bombon)',
                        'Linares',
                        'Oyacachi',
                        'Santa Rosa',
                        'Sardinas',
                        'Baeza',
                        'Cosanga',
                        'Cuyuga',
                        'Papallacta',
                        'San Francisco de Borja (Virgilio Davila)',
                        'Sumaco',
                        'Carlos Julio Arosemena Tola',
                        'Puyo',
                        'Canelos',
                        'Diez de Agosto',
                        'Fatima',
                        'Montalvo (Andoas)',
                        'Pomona',
                        'Rio Corrientes',
                        'Rio Tigre',
                        'Sarayacu',
                        'Simon Bolivar (Cab. En Mushullacta)',
                        'Tarqui',
                        'Teniente Hugo Ortiz',
                        'Veracruz (Cab. En Indillama)',
                        'El Triunfo',
                        'Mera',
                        'Madre Tierra',
                        'Shell',
                        'Santa Clara',
                        'San Jose',
                        'Arajuno',
                        'Curaray',
                        'Belisario Quevedo',
                        'Carcelen',
                        'Centro Historico',
                        'Cochapamba',
                        'Comite del Pueblo',
                        'Cotocollao',
                        'Chilibulo',
                        'Chillogallo',
                        'Chimbacalle',
                        'El Condado',
                        'Guamani',
                        'Inaquito',
                        'Itchimbia',
                        'Jipijapa',
                        'Kennedy',
                        'La Argelia',
                        'La Concepcion',
                        'La Ecuatoriana',
                        'La Ferroviaria',
                        'La Libertad',
                        'La Magdalena',
                        'La Mena',
                        'Mariscal Sucre',
                        'Ponceano',
                        'Puengasi',
                        'Quitumbe',
                        'Rumipamba',
                        'San Bartolo',
                        'San Isidro del Inca',
                        'San Juan',
                        'Solanda',
                        'Turubamba',
                        'Quito Distrito Metropolitano , Cabecera',
                        'Alangasi',
                        'Amaguaña',
                        'Atahualpa (Habaspamba)',
                        'Calacali',
                        'Calderon (Carapungo)',
                        'Conocoto',
                        'Cumbaya',
                        'Chavezpamba',
                        'Checa (Chilpa)',
                        'El Quinche',
                        'Gualea',
                        'Guangopolo',
                        'Guayllabamba',
                        'La Merced',
                        'Llano Chico',
                        'Lloa',
                        'Nanegal',
                        'Nanegalito',
                        'Nayon',
                        'Nono',
                        'Pacto',
                        'Perucho',
                        'Pifo',
                        'Pintag',
                        'Pomasqui',
                        'Puellaro',
                        'Puembo',
                        'San Antonio',
                        'San Jose de Minas',
                        'Tababela',
                        'Tumbaco',
                        'Yaruqui',
                        'Zambiza',
                        'Ayora',
                        'Cayambe',
                        'Juan Montalvo',
                        'Cayambe',
                        'Ascazubi',
                        'Cangahua',
                        'Olmedo (Pesillo)',
                        'Oton',
                        'Santa Rosa de Cuzubamba',
                        'Machachi',
                        'Aloag',
                        'Aloasi',
                        'Cutuglagua',
                        'El Chaupi',
                        'Manuel Cornejo Astorga (Tandapi)',
                        'Tambillo',
                        'Uyumbicho',
                        'Tabacundo',
                        'La Esperanza',
                        'Malchingui',
                        'Tocachi',
                        'Tupigachi',
                        'Sangolqui',
                        'San Pedro de Taboada',
                        'San Rafael',
                        'Sangolqui',
                        'Cotogchoa',
                        'Rumipamba',
                        'San Miguel de los Bancos',
                        'Mindo',
                        'Pedro Vicente Maldonado',
                        'Puerto Quito',
                        'Atocha - Ficoa',
                        'Celiano Monge',
                        'Huachi Chico',
                        'Huachi Loreto',
                        'La Merced',
                        'La Peninsula',
                        'Matriz',
                        'Pishilata',
                        'San Francisco',
                        'Ambato',
                        'Ambatillo',
                        'Atahualpa (Chisalata)',
                        'Augusto N. Martinez (Mundugleo)',
                        'Constatino Fernandez (Cab. Em Cullitahua)',
                        'Huachi Grande',
                        'Izamba',
                        'Juan Benigno Vela',
                        'Montalvo',
                        'Pasa',
                        'Picaigua',
                        'Pilagüin (Pilahuin)',
                        'Quisapincha (Quizapincha)',
                        'San Bartolome de Pinllog',
                        'San Fernando (Pasa San Fernando)',
                        'Santa Rosa',
                        'Totoras',
                        'Cunchibamba',
                        'Unamuncho',
                        'Baños de Agua Santa',
                        'Lligua',
                        'Rio Negro',
                        'Rio Verde',
                        'Ulba',
                        'Cevallos',
                        'Mocha',
                        'Pinguili',
                        'Patate',
                        'El Triunfo',
                        'Los Andes (Cab. En Poatug)',
                        'Sucre (Cab. En Sucre - Patate Urco)',
                        'Quero',
                        'Rumipamba',
                        'Yanayacu - Mochapata (Cab. En Yanayacu)',
                        'Pelileo',
                        'Pelileo Grande',
                        'Pelileo',
                        'Benitez (Pachanlica)',
                        'Bolivar',
                        'Cotalo',
                        'Chiquica (Cab. En Chiquica Grande)',
                        'El Rosario (Rumichaca)',
                        'Garcia Moreno (Chumaqui)',
                        'Guambalo (Huambalo)',
                        'Salasaca',
                        'Ciudad Nueva',
                        'Pillaro',
                        'Pillaro',
                        'Baquerizo Moreno',
                        'Emilio Maria Teran (Rumipamba)',
                        'Marcos Espinel (Chacata)',
                        'Presidente Urbina (Chagrama - Patzucul)',
                        'San Andres',
                        'San Jose de Poalo',
                        'San Miguelito',
                        'Tisaleo',
                        'Quinchicoto',
                        'El Limon',
                        'Zamora',
                        'Zamora',
                        'Cumbaratza',
                        'Guadalupe',
                        'Imbana (La Victoria de Imbana)',
                        'Sabanilla',
                        'Timbara',
                        'San Carlos de las Minas',
                        'Zumba',
                        'Chito',
                        'El Chorro',
                        'La Chonta',
                        'Pucapamba',
                        'San Andres',
                        'Guayzimi',
                        'Zurmi',
                        'Nuevo Paraiso',
                        '28 de Mayo (San Jose de Yacuambi)',
                        'La Paz',
                        'San Andres',
                        'Yantzaza (Yanzatza)',
                        'Chicaña',
                        'Los Encuentros',
                        'El Pangui',
                        'El Guisme',
                        'Pachicutza',
                        'Tundayme',
                        'Zumbi',
                        'Palanda',
                        'El Porvenir del Carmen',
                        'San Francisco del Vergel',
                        'Valladolid',
                        'La Canela',
                        'Paquisha',
                        'Bellavista',
                        'Nuevo Quito',
                        'Puerto Baquerizo Moreno',
                        'El Progreso',
                        'Isla Santa Maria (Floreana)',
                        'Puerto Villamil',
                        'Tomas de Berlanga',
                        'Puerto Ayora',
                        'Bellavista',
                        'Santa Rosa',
                        'Nueva Loja',
                        'Dureno',
                        'General Farfan',
                        'El Eno',
                        'Pacayacu',
                        'Jambeli',
                        'Santa Cecilia',
                        'Lumbaqui',
                        'El Reventador',
                        'Gonzalo Pizarro',
                        'Puerto Libre',
                        'Puerto El Carmen del Putumayo',
                        'Palma Roja',
                        'Puerto Bolivar',
                        'Puerto Rodriguez',
                        'Santa Elena',
                        'Shushufindi',
                        'Limoncocha',
                        'Pañacocha',
                        'San Roque',
                        'San Pedro de los Cofanes',
                        'Siete de Julio',
                        'La Bonita',
                        'El Playon de San Francisco',
                        'La Sofia',
                        'Rosa Florida',
                        'Santa Barbara',
                        'El Dorado de Cascales',
                        'Santa Rosa de Sumbios',
                        'Sevilla',
                        'Tarapoa',
                        'Cuyabeno',
                        'Aguas Negras',
                        'Puerto Francisco de Orellana  (El Coca)',
                        'Dayuma',
                        'Taracoa',
                        'Alejandro Labaca',
                        'El Dorado',
                        'El Eden',
                        'Garcia Moreno',
                        'Ines Arango',
                        'La Belleza',
                        'Nuevo Paraiso',
                        'San Jose de Guayusa',
                        'San Luis de Armenia',
                        'Nuevo Rocafuerte',
                        'Capitan Augusto Rivadeneyra',
                        'Conocaco',
                        'Santa Maria de Huiririma',
                        'Tiputini',
                        'Yasuni',
                        'La Joya de los Sachas',
                        'Enokanki',
                        'Pompeya',
                        'San Carlos',
                        'San Sebastian del Coca',
                        'Lago San Pedro',
                        'Rumipamba',
                        'Tres de Noviembre',
                        'Union Milagreña',
                        'Loreto','Avila',
                        'Puerto Murialdo',
                        'San Jose de Payamino',
                        'San Jose de Dahuano',
                        'San Jose de Huaticocha',
                        'Abraham Calazacon',
                        'Bomboli',
                        'Chiguilpe',
                        'Rio Toachi',
                        'Rio Verde',
                        'Santo Domingo de los Colorados',
                        'Zaracay',
                        'Santo Domingo de los Colorados',
                        'Alluriquin',
                        'Puerto Limon',
                        'Luz de America',
                        'San Jacinto del Bua',
                        'Valle Hermoso',
                        'El Esfuerzo',
                        'Santa Maria del Toachi',
                        'Ballenita',
                        'Santa Elena',
                        'Santa Elena',
                        'Atahualpa',
                        'Colonche',
                        'Chanduy',
                        'Manglaralto',
                        'Simon Bolivar (Julio Moreno)',
                        'San Jose de Ancon',
                        'La Libertad',
                        'Carlos Espinoza Larrea',
                        'Gral. Alberto Enriquez Gallo',
                        'Vicente Rocafuerte',
                        'Santa Rosa',
                        'Anconcito',]
        self.listParr=tk.OptionMenu(self.frame2,self.cparroquia,*self.parroquias)
        self.listParr.config(width=15, height=1,bg= "white")
        self.listParr.grid(column=2,row=5)


        self.label = tk.Label(self.frame2, text='Colegio', fg='white',bg ='#4779b2', font=('Rockwell',11,'bold'))
        self.label.grid(column=1,row=6)
        self.ccolegio = tk.StringVar()
        self.custcolegio = tk.Entry(self.frame2, textvariable=self.ccolegio,width=21)
        self.custcolegio.grid(column=2,row=6)

        self.creategrid(0)

        self.control = tk.Label(self.frame4, text = 'Controles',fg='white', bg ='#4779b2', font=('Rockwell',12,'bold'))
        self.control.grid(columnspan=4, column=0,row=0, pady=10,padx=0)

        self.savebtn = tk.Button(self.frame4,text='GUARDAR', font=('Arial',10,'bold'), bg='#8da9c9', command=self.guarda)
        self.savebtn.grid(column=0,row=1, pady=10,padx=0)

        self.limpia = tk.Button(self.frame4,text='LIMPIAR', font=('Arial',10,'bold'), bg='#8da9c9', command=self.limpiar)
        self.limpia.grid(column=1,row=1, pady=10,padx=0)

        self.savebtn = tk.Button(self.frame4,text='ELIMINAR', font=('Arial',10,'bold'), bg='#8da9c9', command=self.elimina)
        self.savebtn.grid(column=2,row=1, pady=10,padx=0)

        self.savebtn = tk.Button(self.frame4,text='MODIFICAR', font=('Arial',10,'bold'), bg='#8da9c9', command=self.modifica)
        self.savebtn.grid(columnspan=3,column=0,row=3, pady=10,padx=0)

        self.window.mainloop()

if __name__ == "__main__":
    BaseData()
